name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: publish on version change
        id: Publish_Nuget_Crystal_EntityFrameworkCore
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Crystal.EntityFrameworkCore/Crystal.EntityFrameworkCore.csproj

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          
      - name: publish on version change
        id: Publish_Nuget_Crystal_Dapper
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Crystal.Dapper/Crystal.Dapper.csproj

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          
      - name: publish on version change
        id: Publish_Nuget_Crystal_Shared
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Crystal.Shared/Crystal.Shared.csproj

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_KEY}}

        
